# Generated by Django 4.1.3 on 2022-11-14 20:09

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('base_yield', models.CharField(blank=True, help_text='The total weight of the base ingredients', max_length=50, null=True, verbose_name='Yield')),
                ('base_recipe_portions', models.IntegerField(blank=True, help_text='Amount of portions (people) the recipe is designed to serve', null=True)),
                ('base_type', models.CharField(blank=True, help_text='Type of recipe: Base (Sauce, Dressing),Compound (Complete Dish),Batch (Large Volume Base Recipe),', max_length=50, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('preparation', models.TextField(blank=True, null=True)),
                ('allergen', models.ManyToManyField(blank=True, to='recipes_app.allergen')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('note', models.CharField(blank=True, max_length=120, null=True)),
                ('order_index', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='FoodPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('order_index', models.PositiveIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='грама', max_length=20, null=True)),
                ('amount_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='amount_number', to='recipes_app.amount')),
                ('base', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='base', to='recipes_app.baserecipe')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('order_index', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PreparationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('minute', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('summary', models.CharField(blank=True, help_text='Summary for waiters!', max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('finish', models.CharField(blank=True, max_length=150, null=True)),
                ('season', models.CharField(blank=True, choices=[('spring', 'spring'), ('summer', 'summer'), ('autumn', 'autumn'), ('winter', 'winter')], max_length=6, null=True)),
                ('preparation_time', models.CharField(blank=True, max_length=100, null=True)),
                ('release_time', models.CharField(blank=True, max_length=100, null=True)),
                ('serving_value', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('order_index', models.PositiveIntegerField(blank=True, null=True)),
                ('allergen', models.ManyToManyField(blank=True, to='recipes_app.allergen')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes_app.category')),
                ('food_plate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes_app.foodplate')),
                ('image_recipe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='image_recipe', to='recipes_app.photo')),
                ('ingredient', models.ManyToManyField(blank=True, to='recipes_app.ingredient')),
                ('preparation_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes_app.preparationmethod')),
                ('video_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='video_recipe', to='recipes_app.video')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='preparation_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes_app.preparationmethod'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='image_category', to='recipes_app.photo'),
        ),
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipes_app.menu'),
        ),
        migrations.AddField(
            model_name='baserecipe',
            name='ingredient',
            field=models.ManyToManyField(blank=True, to='recipes_app.ingredient'),
        ),
        migrations.AddField(
            model_name='baserecipe',
            name='preparation_method',
            field=models.ManyToManyField(blank=True, to='recipes_app.preparationmethod'),
        ),
    ]
