# Generated by Django 4.1.3 on 2022-11-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseingredient',
            name='base',
        ),
        migrations.AlterField(
            model_name='baserecipe',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
