# Generated by Django 4.1.3 on 2022-11-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0002_remove_baserecipe_ingredient_alter_baserecipe_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseingredient',
            options={'ordering': ('order_index', 'id')},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order_index', 'id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['order_index', 'id']},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['order_index', 'id']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['order_index', 'id']},
        ),
    ]
