# Generated by Django 4.1.3 on 2022-11-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amount',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['order_index', 'id', 'title']},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='finish',
            field=models.CharField(blank=True, help_text='Final touches to the dish', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.CharField(blank=True, help_text='Time needed to prepare the recipe', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='release_time',
            field=models.CharField(blank=True, help_text='Release time from standard', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serving_value',
            field=models.IntegerField(blank=True, help_text='Serving size from menu', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
