# Generated by Django 4.1.3 on 2022-11-16 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0003_alter_amount_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergen',
            options={'ordering': ('title',)},
        ),
    ]
