# Generated by Django 4.1.3 on 2022-11-26 07:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0003_alter_baseingredient_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
