# Generated by Django 4.1.3 on 2022-11-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0004_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='image_category', to='recipes_app.photo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='image_recipe', to='recipes_app.photo'),
        ),
    ]
