# Generated by Django 4.1.3 on 2022-12-26 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0005_alter_category_image_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_activ',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='baseingredient',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recipes_app.baserecipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base', to='recipes_app.baserecipe'),
        ),
    ]
