# Generated by Django 4.1.3 on 2022-11-27 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_app', '0002_appuser_date_joined_appuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alias', models.EmailField(blank=True, default='', max_length=70)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
            ],
        ),
    ]
