# Generated by Django 4.1.3 on 2022-11-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_customgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
