# Generated by Django 4.1.3 on 2022-11-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=300)),
                ('second_title', models.CharField(blank=True, max_length=300, null=True)),
                ('content_title', models.CharField(max_length=300)),
                ('content_paragraph', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='recipecomment',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='recipecomment',
            name='text',
            field=models.TextField(verbose_name='Comment:'),
        ),
    ]
