# Generated by Django 4.1.3 on 2022-11-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_homepage_alter_recipecomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='second_title',
            field=models.CharField(blank=True, help_text='hide when user logs in', max_length=300, null=True),
        ),
    ]
