# Generated by Django 4.1.3 on 2022-11-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_homepage_second_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
